# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-11-29 07:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('proveedor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'Categoria',
                'verbose_name_plural': 'Categorias',
            },
        ),
        migrations.CreateModel(
            name='InsercionInmediata',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('observacion', models.CharField(blank=True, max_length=50)),
                ('fecha_hora', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Insercion Inmediata',
                'verbose_name_plural': 'Inserciones Inmediatas',
            },
        ),
        migrations.CreateModel(
            name='PrecioCompraProducto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precio_compra', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Precio de compra')),
                ('factor_conversion', models.DecimalField(decimal_places=2, help_text='Numero a multiplicar para convertir en la unidad de medida principal', max_digits=15, verbose_name='Factor de conversion')),
            ],
            options={
                'verbose_name': 'otro precio de compra',
                'verbose_name_plural': 'otros precios de compra',
            },
        ),
        migrations.CreateModel(
            name='PrecioVentaProducto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precio_venta', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Precio de venta')),
                ('factor_conversion', models.DecimalField(decimal_places=2, help_text='Numero a multiplicar para convertir en la unidad de medida principal', max_digits=15, verbose_name='Factor de conversion')),
            ],
            options={
                'verbose_name': 'Otro precio de venta',
                'verbose_name_plural': 'Otros precios de venta',
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=50, unique=True)),
                ('nombre', models.CharField(max_length=200, unique=True)),
                ('iva', models.CharField(choices=[('IVA10', 'IVA 10%'), ('IVA5', 'IVA 5%'), ('EXENTA', 'EXENTA')], default='IVA10', max_length=10, verbose_name='IVA')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='producto.Categoria')),
                ('proveedor', models.ManyToManyField(blank=True, to='proveedor.Proveedor')),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
            },
        ),
        migrations.CreateModel(
            name='SustraccionInmediata',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('observacion', models.CharField(blank=True, max_length=50)),
                ('fecha_hora', models.DateTimeField(auto_now_add=True)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='producto.Producto')),
            ],
            options={
                'verbose_name': 'Sustraccion Inmediata',
                'verbose_name_plural': 'Sustracciones Inmediatas',
            },
        ),
        migrations.CreateModel(
            name='UnidadMedida',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True)),
                ('abreviatura', models.CharField(max_length=10, unique=True)),
            ],
            options={
                'verbose_name': 'Unidad de medida',
                'verbose_name_plural': 'Unidades de medida',
            },
        ),
        migrations.AddField(
            model_name='producto',
            name='unidad_medida',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='producto.UnidadMedida'),
        ),
        migrations.AddField(
            model_name='precioventaproducto',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='producto.Producto'),
        ),
        migrations.AddField(
            model_name='precioventaproducto',
            name='unidad_medida',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='producto.UnidadMedida'),
        ),
        migrations.AddField(
            model_name='preciocompraproducto',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='producto.Producto'),
        ),
        migrations.AddField(
            model_name='preciocompraproducto',
            name='unidad_medida',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='producto.UnidadMedida'),
        ),
        migrations.AddField(
            model_name='insercioninmediata',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='producto.Producto'),
        ),
    ]
