# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-08-31 10:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('venta', '0003_auto_20170831_0645'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='venta',
            options={'permissions': (('ver_ventas_todo', 'Puede ver todas las ventas'), ('ver_ventas_dia', 'Puede ver las ventas del dia')), 'verbose_name': 'Venta', 'verbose_name_plural': 'Ventas'},
        ),
    ]
